log4r_config:
  loggers:
    - name      : production
      level     : INFO
      trace     : 'false'
      outputters:
        - stdout
    
    - name      : development
      level     : DEBUG
      trace     : 'true'
      outputters:
        - stdout
        
  outputters:
    - type     : StdoutOutputter
      name     : stdout
      formatter:
        date_pattern: '%Y-%m-%d %H:%M:%S'
        pattern     : '%d %l: %m '
        type        : PatternFormatter